/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Acme.App.MastercardApi.Client.Api;
using Acme.App.MastercardApi.Client.Model;
using Acme.App.MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Acme.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing AddMerchantResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddMerchantResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddMerchantResponse
        //private AddMerchantResponse instance;

        public AddMerchantResponseTests()
        {
            // TODO uncomment below to create an instance of AddMerchantResponse
            //instance = new AddMerchantResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddMerchantResponse
        /// </summary>
        [Fact]
        public void AddMerchantResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddMerchantResponse
            //Assert.IsType<AddMerchantResponse>(instance);
        }


        /// <summary>
        /// Test the property 'MerchantReferenceNumber'
        /// </summary>
        [Fact]
        public void MerchantReferenceNumberTest()
        {
            // TODO unit test for the property 'MerchantReferenceNumber'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
