/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Acme.App.MastercardApi.Client.Api;
using Acme.App.MastercardApi.Client.Model;
using Acme.App.MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Acme.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing AddTerminatedMerchantResponseSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddTerminatedMerchantResponseSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddTerminatedMerchantResponseSchema
        //private AddTerminatedMerchantResponseSchema instance;

        public AddTerminatedMerchantResponseSchemaTests()
        {
            // TODO uncomment below to create an instance of AddTerminatedMerchantResponseSchema
            //instance = new AddTerminatedMerchantResponseSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddTerminatedMerchantResponseSchema
        /// </summary>
        [Fact]
        public void AddTerminatedMerchantResponseSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddTerminatedMerchantResponseSchema
            //Assert.IsType<AddTerminatedMerchantResponseSchema>(instance);
        }


        /// <summary>
        /// Test the property 'AddMerchantResponse'
        /// </summary>
        [Fact]
        public void AddMerchantResponseTest()
        {
            // TODO unit test for the property 'AddMerchantResponse'
        }

    }

}
