/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Acme.App.MastercardApi.Client.Api;
using Acme.App.MastercardApi.Client.Model;
using Acme.App.MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Acme.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DriversLicense
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DriversLicenseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DriversLicense
        //private DriversLicense instance;

        public DriversLicenseTests()
        {
            // TODO uncomment below to create an instance of DriversLicense
            //instance = new DriversLicense();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DriversLicense
        /// </summary>
        [Fact]
        public void DriversLicenseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DriversLicense
            //Assert.IsType<DriversLicense>(instance);
        }


        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Fact]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'CountrySubdivision'
        /// </summary>
        [Fact]
        public void CountrySubdivisionTest()
        {
            // TODO unit test for the property 'CountrySubdivision'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

    }

}
