/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Acme.App.MastercardApi.Client.Api;
using Acme.App.MastercardApi.Client.Model;
using Acme.App.MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Acme.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing InquiredMerchantMerchant
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InquiredMerchantMerchantTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InquiredMerchantMerchant
        //private InquiredMerchantMerchant instance;

        public InquiredMerchantMerchantTests()
        {
            // TODO uncomment below to create an instance of InquiredMerchantMerchant
            //instance = new InquiredMerchantMerchant();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InquiredMerchantMerchant
        /// </summary>
        [Fact]
        public void InquiredMerchantMerchantInstanceTest()
        {
            // TODO uncomment below to test "IsType" InquiredMerchantMerchant
            //Assert.IsType<InquiredMerchantMerchant>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DoingBusinessAsName'
        /// </summary>
        [Fact]
        public void DoingBusinessAsNameTest()
        {
            // TODO unit test for the property 'DoingBusinessAsName'
        }
        /// <summary>
        /// Test the property 'AddedByAcquirerID'
        /// </summary>
        [Fact]
        public void AddedByAcquirerIDTest()
        {
            // TODO unit test for the property 'AddedByAcquirerID'
        }
        /// <summary>
        /// Test the property 'AddedOnDate'
        /// </summary>
        [Fact]
        public void AddedOnDateTest()
        {
            // TODO unit test for the property 'AddedOnDate'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'AltPhoneNumber'
        /// </summary>
        [Fact]
        public void AltPhoneNumberTest()
        {
            // TODO unit test for the property 'AltPhoneNumber'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'CountrySubdivisionTaxId'
        /// </summary>
        [Fact]
        public void CountrySubdivisionTaxIdTest()
        {
            // TODO unit test for the property 'CountrySubdivisionTaxId'
        }
        /// <summary>
        /// Test the property 'NationalTaxId'
        /// </summary>
        [Fact]
        public void NationalTaxIdTest()
        {
            // TODO unit test for the property 'NationalTaxId'
        }
        /// <summary>
        /// Test the property 'ServiceProvLegal'
        /// </summary>
        [Fact]
        public void ServiceProvLegalTest()
        {
            // TODO unit test for the property 'ServiceProvLegal'
        }
        /// <summary>
        /// Test the property 'ServiceProvDBA'
        /// </summary>
        [Fact]
        public void ServiceProvDBATest()
        {
            // TODO unit test for the property 'ServiceProvDBA'
        }
        /// <summary>
        /// Test the property 'TerminationReasonCode'
        /// </summary>
        [Fact]
        public void TerminationReasonCodeTest()
        {
            // TODO unit test for the property 'TerminationReasonCode'
        }
        /// <summary>
        /// Test the property 'UrlGroup'
        /// </summary>
        [Fact]
        public void UrlGroupTest()
        {
            // TODO unit test for the property 'UrlGroup'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Principal'
        /// </summary>
        [Fact]
        public void PrincipalTest()
        {
            // TODO unit test for the property 'Principal'
        }
        /// <summary>
        /// Test the property 'SearchCriteria'
        /// </summary>
        [Fact]
        public void SearchCriteriaTest()
        {
            // TODO unit test for the property 'SearchCriteria'
        }
        /// <summary>
        /// Test the property 'MerchantMatch'
        /// </summary>
        [Fact]
        public void MerchantMatchTest()
        {
            // TODO unit test for the property 'MerchantMatch'
        }

    }

}
