/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Acme.App.MastercardApi.Client.Api;
using Acme.App.MastercardApi.Client.Model;
using Acme.App.MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Acme.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing MerchantMatch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MerchantMatchTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MerchantMatch
        //private MerchantMatch instance;

        public MerchantMatchTests()
        {
            // TODO uncomment below to create an instance of MerchantMatch
            //instance = new MerchantMatch();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MerchantMatch
        /// </summary>
        [Fact]
        public void MerchantMatchInstanceTest()
        {
            // TODO uncomment below to test "IsType" MerchantMatch
            //Assert.IsType<MerchantMatch>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DoingBusinessAsName'
        /// </summary>
        [Fact]
        public void DoingBusinessAsNameTest()
        {
            // TODO unit test for the property 'DoingBusinessAsName'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'AltPhoneNumber'
        /// </summary>
        [Fact]
        public void AltPhoneNumberTest()
        {
            // TODO unit test for the property 'AltPhoneNumber'
        }
        /// <summary>
        /// Test the property 'CountrySubdivisionTaxId'
        /// </summary>
        [Fact]
        public void CountrySubdivisionTaxIdTest()
        {
            // TODO unit test for the property 'CountrySubdivisionTaxId'
        }
        /// <summary>
        /// Test the property 'NationalTaxId'
        /// </summary>
        [Fact]
        public void NationalTaxIdTest()
        {
            // TODO unit test for the property 'NationalTaxId'
        }
        /// <summary>
        /// Test the property 'ServiceProvLegal'
        /// </summary>
        [Fact]
        public void ServiceProvLegalTest()
        {
            // TODO unit test for the property 'ServiceProvLegal'
        }
        /// <summary>
        /// Test the property 'ServiceProvDBA'
        /// </summary>
        [Fact]
        public void ServiceProvDBATest()
        {
            // TODO unit test for the property 'ServiceProvDBA'
        }
        /// <summary>
        /// Test the property 'PrincipalMatch'
        /// </summary>
        [Fact]
        public void PrincipalMatchTest()
        {
            // TODO unit test for the property 'PrincipalMatch'
        }
        /// <summary>
        /// Test the property 'UrlMatch'
        /// </summary>
        [Fact]
        public void UrlMatchTest()
        {
            // TODO unit test for the property 'UrlMatch'
        }

    }

}
