/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Acme.App.MastercardApi.Client.Api;
using Acme.App.MastercardApi.Client.Model;
using Acme.App.MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Acme.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PrincipalMatch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PrincipalMatchTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PrincipalMatch
        //private PrincipalMatch instance;

        public PrincipalMatchTests()
        {
            // TODO uncomment below to create an instance of PrincipalMatch
            //instance = new PrincipalMatch();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PrincipalMatch
        /// </summary>
        [Fact]
        public void PrincipalMatchInstanceTest()
        {
            // TODO uncomment below to test "IsType" PrincipalMatch
            //Assert.IsType<PrincipalMatch>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'AltPhoneNumber'
        /// </summary>
        [Fact]
        public void AltPhoneNumberTest()
        {
            // TODO unit test for the property 'AltPhoneNumber'
        }
        /// <summary>
        /// Test the property 'NationalId'
        /// </summary>
        [Fact]
        public void NationalIdTest()
        {
            // TODO unit test for the property 'NationalId'
        }
        /// <summary>
        /// Test the property 'DriversLicense'
        /// </summary>
        [Fact]
        public void DriversLicenseTest()
        {
            // TODO unit test for the property 'DriversLicense'
        }

    }

}
