/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Acme.App.MastercardApi.Client.Api;
using Acme.App.MastercardApi.Client.Model;
using Acme.App.MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Acme.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing RetroInquiryResponseSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RetroInquiryResponseSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RetroInquiryResponseSchema
        //private RetroInquiryResponseSchema instance;

        public RetroInquiryResponseSchemaTests()
        {
            // TODO uncomment below to create an instance of RetroInquiryResponseSchema
            //instance = new RetroInquiryResponseSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RetroInquiryResponseSchema
        /// </summary>
        [Fact]
        public void RetroInquiryResponseSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" RetroInquiryResponseSchema
            //Assert.IsType<RetroInquiryResponseSchema>(instance);
        }


        /// <summary>
        /// Test the property 'RetroInquiryResponse'
        /// </summary>
        [Fact]
        public void RetroInquiryResponseTest()
        {
            // TODO unit test for the property 'RetroInquiryResponse'
        }

    }

}
