/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Acme.App.MastercardApi.Client.Api;
using Acme.App.MastercardApi.Client.Model;
using Acme.App.MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Acme.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing RetroInquiryRequestSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RetroInquiryRequestSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RetroInquiryRequestSchema
        //private RetroInquiryRequestSchema instance;

        public RetroInquiryRequestSchemaTests()
        {
            // TODO uncomment below to create an instance of RetroInquiryRequestSchema
            //instance = new RetroInquiryRequestSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RetroInquiryRequestSchema
        /// </summary>
        [Fact]
        public void RetroInquiryRequestSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" RetroInquiryRequestSchema
            //Assert.IsType<RetroInquiryRequestSchema>(instance);
        }


        /// <summary>
        /// Test the property 'RetroInquiryRequest'
        /// </summary>
        [Fact]
        public void RetroInquiryRequestTest()
        {
            // TODO unit test for the property 'RetroInquiryRequest'
        }

    }

}
