/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Acme.App.MastercardApi.Client.Api;
using Acme.App.MastercardApi.Client.Model;
using Acme.App.MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Acme.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SearchCriteria
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchCriteriaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchCriteria
        //private SearchCriteria instance;

        public SearchCriteriaTests()
        {
            // TODO uncomment below to create an instance of SearchCriteria
            //instance = new SearchCriteria();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchCriteria
        /// </summary>
        [Fact]
        public void SearchCriteriaInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchCriteria
            //Assert.IsType<SearchCriteria>(instance);
        }


        /// <summary>
        /// Test the property 'SearchAll'
        /// </summary>
        [Fact]
        public void SearchAllTest()
        {
            // TODO unit test for the property 'SearchAll'
        }
        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Fact]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'MinPossibleMatchCount'
        /// </summary>
        [Fact]
        public void MinPossibleMatchCountTest()
        {
            // TODO unit test for the property 'MinPossibleMatchCount'
        }

    }

}
