/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Acme.App.MastercardApi.Client.Api;
using Acme.App.MastercardApi.Client.Model;
using Acme.App.MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Acme.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TerminationInquiry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TerminationInquiryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TerminationInquiry
        //private TerminationInquiry instance;

        public TerminationInquiryTests()
        {
            // TODO uncomment below to create an instance of TerminationInquiry
            //instance = new TerminationInquiry();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TerminationInquiry
        /// </summary>
        [Fact]
        public void TerminationInquiryInstanceTest()
        {
            // TODO uncomment below to test "IsType" TerminationInquiry
            //Assert.IsType<TerminationInquiry>(instance);
        }


        /// <summary>
        /// Test the property 'PageOffset'
        /// </summary>
        [Fact]
        public void PageOffsetTest()
        {
            // TODO unit test for the property 'PageOffset'
        }
        /// <summary>
        /// Test the property 'Ref'
        /// </summary>
        [Fact]
        public void RefTest()
        {
            // TODO unit test for the property 'Ref'
        }
        /// <summary>
        /// Test the property 'TransactionReferenceNumber'
        /// </summary>
        [Fact]
        public void TransactionReferenceNumberTest()
        {
            // TODO unit test for the property 'TransactionReferenceNumber'
        }
        /// <summary>
        /// Test the property 'PossibleMerchantMatches'
        /// </summary>
        [Fact]
        public void PossibleMerchantMatchesTest()
        {
            // TODO unit test for the property 'PossibleMerchantMatches'
        }
        /// <summary>
        /// Test the property 'PossibleInquiryMatches'
        /// </summary>
        [Fact]
        public void PossibleInquiryMatchesTest()
        {
            // TODO unit test for the property 'PossibleInquiryMatches'
        }

    }

}
