/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Acme.App.MastercardApi.Client.Api;
using Acme.App.MastercardApi.Client.Model;
using Acme.App.MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Acme.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TerminatedMerchant
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TerminatedMerchantTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TerminatedMerchant
        //private TerminatedMerchant instance;

        public TerminatedMerchantTests()
        {
            // TODO uncomment below to create an instance of TerminatedMerchant
            //instance = new TerminatedMerchant();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TerminatedMerchant
        /// </summary>
        [Fact]
        public void TerminatedMerchantInstanceTest()
        {
            // TODO uncomment below to test "IsType" TerminatedMerchant
            //Assert.IsType<TerminatedMerchant>(instance);
        }


        /// <summary>
        /// Test the property 'Merchant'
        /// </summary>
        [Fact]
        public void MerchantTest()
        {
            // TODO unit test for the property 'Merchant'
        }
        /// <summary>
        /// Test the property 'MerchantMatch'
        /// </summary>
        [Fact]
        public void MerchantMatchTest()
        {
            // TODO unit test for the property 'MerchantMatch'
        }

    }

}
