/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Acme.App.MastercardApi.Client.Api;
using Acme.App.MastercardApi.Client.Model;
using Acme.App.MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Acme.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UrlGroup
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UrlGroupTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UrlGroup
        //private UrlGroup instance;

        public UrlGroupTests()
        {
            // TODO uncomment below to create an instance of UrlGroup
            //instance = new UrlGroup();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UrlGroup
        /// </summary>
        [Fact]
        public void UrlGroupInstanceTest()
        {
            // TODO uncomment below to test "IsType" UrlGroup
            //Assert.IsType<UrlGroup>(instance);
        }


        /// <summary>
        /// Test the property 'ExactMatchUrls'
        /// </summary>
        [Fact]
        public void ExactMatchUrlsTest()
        {
            // TODO unit test for the property 'ExactMatchUrls'
        }
        /// <summary>
        /// Test the property 'CloseMatchUrls'
        /// </summary>
        [Fact]
        public void CloseMatchUrlsTest()
        {
            // TODO unit test for the property 'CloseMatchUrls'
        }
        /// <summary>
        /// Test the property 'NoMatchUrls'
        /// </summary>
        [Fact]
        public void NoMatchUrlsTest()
        {
            // TODO unit test for the property 'NoMatchUrls'
        }

    }

}
