/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Acme.App.MastercardApi.Client.Client.OpenAPIDateConverter;

namespace Acme.App.MastercardApi.Client.Model
{
    /// <summary>
    /// RetroInquiryResponseSchema
    /// </summary>
    [DataContract(Name = "RetroInquiryResponseSchema")]
    public partial class RetroInquiryResponseSchema : IEquatable<RetroInquiryResponseSchema>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RetroInquiryResponseSchema" /> class.
        /// </summary>
        /// <param name="retroInquiryResponse">retroInquiryResponse.</param>
        public RetroInquiryResponseSchema(RetroInquiryResponse retroInquiryResponse = default(RetroInquiryResponse))
        {
            this.RetroInquiryResponse = retroInquiryResponse;
        }

        /// <summary>
        /// Gets or Sets RetroInquiryResponse
        /// </summary>
        [DataMember(Name = "RetroInquiryResponse", EmitDefaultValue = false)]
        public RetroInquiryResponse RetroInquiryResponse { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RetroInquiryResponseSchema {\n");
            sb.Append("  RetroInquiryResponse: ").Append(RetroInquiryResponse).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RetroInquiryResponseSchema);
        }

        /// <summary>
        /// Returns true if RetroInquiryResponseSchema instances are equal
        /// </summary>
        /// <param name="input">Instance of RetroInquiryResponseSchema to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RetroInquiryResponseSchema input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.RetroInquiryResponse == input.RetroInquiryResponse ||
                    (this.RetroInquiryResponse != null &&
                    this.RetroInquiryResponse.Equals(input.RetroInquiryResponse))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RetroInquiryResponse != null)
                    hashCode = hashCode * 59 + this.RetroInquiryResponse.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
