/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Acme.App.MastercardApi.Client.Client.OpenAPIDateConverter;

namespace Acme.App.MastercardApi.Client.Model
{
    /// <summary>
    /// Retros
    /// </summary>
    [DataContract(Name = "Retros")]
    public partial class Retros : IEquatable<Retros>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Retros" /> class.
        /// </summary>
        /// <param name="retroactiveInquiryResults">retroactiveInquiryResults.</param>
        public Retros(List<Retro> retroactiveInquiryResults = default(List<Retro>))
        {
            this.RetroactiveInquiryResults = retroactiveInquiryResults;
        }

        /// <summary>
        /// Gets or Sets RetroactiveInquiryResults
        /// </summary>
        [DataMember(Name = "Retroactive-Inquiry-Results", EmitDefaultValue = false)]
        public List<Retro> RetroactiveInquiryResults { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Retros {\n");
            sb.Append("  RetroactiveInquiryResults: ").Append(RetroactiveInquiryResults).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Retros);
        }

        /// <summary>
        /// Returns true if Retros instances are equal
        /// </summary>
        /// <param name="input">Instance of Retros to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Retros input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.RetroactiveInquiryResults == input.RetroactiveInquiryResults ||
                    this.RetroactiveInquiryResults != null &&
                    input.RetroactiveInquiryResults != null &&
                    this.RetroactiveInquiryResults.SequenceEqual(input.RetroactiveInquiryResults)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RetroactiveInquiryResults != null)
                    hashCode = hashCode * 59 + this.RetroactiveInquiryResults.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
