/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Acme.App.MastercardApi.Client.Client;
using Acme.App.MastercardApi.Client.Api;
// uncomment below to import models
//using Acme.App.MastercardApi.Client.Model;

namespace Acme.App.MastercardApi.Client.Test.Api
{
    /// <summary>
    ///  Class for testing AddTerminatedMerchantApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AddTerminatedMerchantApiTests : IDisposable
    {
        private AddTerminatedMerchantApi instance;

        public AddTerminatedMerchantApiTests()
        {
            instance = new AddTerminatedMerchantApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddTerminatedMerchantApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AddTerminatedMerchantApi
            //Assert.IsType<AddTerminatedMerchantApi>(instance);
        }

        /// <summary>
        /// Test AddMerchantPost
        /// </summary>
        [Fact]
        public void AddMerchantPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string format = null;
            //AddTerminatedMerchantRequestSchema addTerminatedMerchantRequestSchema = null;
            //var response = instance.AddMerchantPost(format, addTerminatedMerchantRequestSchema);
            //Assert.IsType<AddTerminatedMerchantResponseSchema>(response);
        }
    }
}
