/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Acme.App.MastercardApi.Client.Client;
using Acme.App.MastercardApi.Client.Api;
using Acme.App.MastercardApi.Client.Model;
// uncomment below to import models
//using Acme.App.MastercardApi.Client.Model;

namespace Acme.App.MastercardApi.Client.Test.Api
{
    /// <summary>
    ///  Class for testing TerminationInquiryHistoryRequestApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TerminationInquiryHistoryRequestApiTests : IDisposable
    {
        private TerminationInquiryHistoryRequestApi instance;

        public TerminationInquiryHistoryRequestApiTests()
        {
            instance = new TerminationInquiryHistoryRequestApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TerminationInquiryHistoryRequestApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TerminationInquiryHistoryRequestApi
            //Assert.IsType<TerminationInquiryHistoryRequestApi>(instance);
        }

        /// <summary>
        /// Test TerminationInquiryIRNGet
        /// </summary>
        [Fact]
        public void TerminationInquiryIRNGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int pageOffset = null;
            //int pageLength = null;
            //string format = null;
            //string acquirerId = null;
            //string IRN = null;
            //var response = instance.TerminationInquiryIRNGet(pageOffset, pageLength, format, acquirerId, IRN);
            //Assert.IsType<TerminationInquirySchema>(response);
        }
    }
}
